# Generated by Django 2.2.7 on 2020-04-26 16:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0002_event_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="creation_date", new_name="created_at",
        ),
        migrations.RemoveField(model_name="event", name="modified_date",),
        migrations.AddField(
            model_name="event",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
