# Generated by Django 2.2.10 on 2020-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="alert_date", new_name="scheduled_at",
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
