# Generated by Django 2.2.10 on 2020-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20200511_2313"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="scheduled_at", new_name="scheduled_time",
        ),
        migrations.AddField(
            model_name="event",
            name="has_reminder_sent",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
