# Generated by Django 2.2.10 on 2020-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20200511_2324"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="alert_interval",),
        migrations.AddField(
            model_name="event",
            name="set_reminder",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="has_reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
