# Generated by Django 2.2.10 on 2020-05-14 18:01

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_auto_20200512_1634"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="scheduled_time",),
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateField(
                default=datetime.datetime(2020, 5, 14, 18, 0, 54, 696515, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="event_time",
            field=models.TimeField(
                default=datetime.datetime(2020, 5, 14, 18, 1, 1, 649912, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
