# Generated by Django 2.2.10 on 2020-05-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_auto_20200515_0017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="event_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event", name="event_time", field=models.TimeField(),
        ),
    ]
